framework:
  github: vlang/v
  version: weekly.2023.50

  bootstrap:
    - cd /opt/vlang && git fetch --all --tags && git checkout tags/weekly.2023.50 && make && v -version && cd /app

  build_flags:
    - -prod -cc clang