framework:
  github: vlang/v
  version: weekly.2024.08 # https://github.com/vlang/v/releases

  bootstrap:
    - cd /opt/vlang && git fetch --all --tags && git checkout tags/weekly.2024.08 && make && v -version && cd /app

  build_flags:
    - -prod -cc gcc
